export const PAISES_ISO = [
  ['AF','Afeganistão'],['ZA','África do Sul'],['AL','Albânia'],['DE','Alemanha'],['AD','Andorra'],
  ['AO','Angola'],['AG','Antígua e Barbuda'],['SA','Arábia Saudita'],['DZ','Argélia'],['AR','Argentina'],
  ['AM','Armênia'],['AU','Austrália'],['AT','Áustria'],['AZ','Azerbaijão'],['BS','Bahamas'],
  ['BH','Bahrein'],['BD','Bangladesh'],['BB','Barbados'],['BE','Bélgica'],['BZ','Belize'],
  ['BJ','Benim'],['BY','Bielorrússia'],['BO','Bolívia'],['BA','Bósnia e Herzegovina'],['BW','Botsuana'],
  ['BR','Brasil'],['BN','Brunei'],['BG','Bulgária'],['BF','Burkina Faso'],['BI','Burundi'],
  ['BT','Butão'],['CV','Cabo Verde'],['CM','Camarões'],['KH','Camboja'],['CA','Canadá'],
  ['QA','Catar'],['KZ','Cazaquistão'],['TD','Chade'],['CL','Chile'],['CN','China'],
  ['CY','Chipre'],['CO','Colômbia'],['KM','Comores'],['CG','Congo'],['CD','Congo (República Democrática)'],
  ['KP','Coreia do Norte'],['KR','Coreia do Sul'],['CI','Costa do Marfim'],['CR','Costa Rica'],['HR','Croácia'],
  ['CU','Cuba'],['DK','Dinamarca'],['DJ','Djibuti'],['DM','Dominica'],['EG','Egito'],
  ['SV','El Salvador'],['AE','Emirados Árabes Unidos'],['EC','Equador'],['ER','Eritreia'],['SK','Eslováquia'],
  ['SI','Eslovênia'],['ES','Espanha'],['US','Estados Unidos'],['EE','Estônia'],['SZ','Essuatíni'],
  ['ET','Etiópia'],['FJ','Fiji'],['PH','Filipinas'],['FI','Finlândia'],['FR','França'],
  ['GA','Gabão'],['GM','Gâmbia'],['GH','Gana'],['GE','Geórgia'],['GD','Granada'],
  ['GR','Grécia'],['GT','Guatemala'],['GY','Guiana'],['GN','Guiné'],['GQ','Guiné Equatorial'],
  ['GW','Guiné-Bissau'],['HT','Haiti'],['HN','Honduras'],['HU','Hungria'],['YE','Iêmen'],
  ['MH','Ilhas Marshall'],['SB','Ilhas Salomão'],['IN','Índia'],['ID','Indonésia'],['IR','Irã'],
  ['IQ','Iraque'],['IE','Irlanda'],['IS','Islândia'],['IL','Israel'],['IT','Itália'],
  ['JM','Jamaica'],['JP','Japão'],['JO','Jordânia'],['KI','Kiribati'],['KW','Kuwait'],
  ['LA','Laos'],['LS','Lesoto'],['LV','Letônia'],['LB','Líbano'],['LR','Libéria'],
  ['LY','Líbia'],['LI','Liechtenstein'],['LT','Lituânia'],['LU','Luxemburgo'],['MK','Macedônia do Norte'],
  ['MG','Madagascar'],['MY','Malásia'],['MW','Maláui'],['MV','Maldivas'],['ML','Mali'],
  ['MT','Malta'],['MA','Marrocos'],['MU','Maurício'],['MR','Mauritânia'],['MX','México'],
  ['FM','Micronésia'],['MZ','Moçambique'],['MD','Moldávia'],['MC','Mônaco'],['MN','Mongólia'],
  ['ME','Montenegro'],['MM','Mianmar'],['NA','Namíbia'],['NR','Nauru'],['NP','Nepal'],
  ['NI','Nicarágua'],['NE','Níger'],['NG','Nigéria'],['NO','Noruega'],['NZ','Nova Zelândia'],
  ['OM','Omã'],['NL','Países Baixos'],['PW','Palau'],['PA','Panamá'],['PG','Papua-Nova Guiné'],
  ['PK','Paquistão'],['PY','Paraguai'],['PE','Peru'],['PL','Polônia'],['PT','Portugal'],
  ['KE','Quênia'],['KG','Quirguistão'],['GB','Reino Unido'],['CF','República Centro-Africana'],['CZ','Tchéquia'],
  ['DO','República Dominicana'],['RO','Romênia'],['RW','Ruanda'],['RU','Rússia'],['WS','Samoa'],
  ['SM','San Marino'],['LC','Santa Lúcia'],['KN','São Cristóvão e Névis'],['ST','São Tomé e Príncipe'],['VC','São Vicente e Granadinas'],
  ['SN','Senegal'],['SL','Serra Leoa'],['RS','Sérvia'],['SC','Seicheles'],['SG','Singapura'],
  ['SY','Síria'],['SO','Somália'],['LK','Sri Lanka'],['SD','Sudão'],['SS','Sudão do Sul'],
  ['SE','Suécia'],['CH','Suíça'],['SR','Suriname'],['TJ','Tajiquistão'],['TH','Tailândia'],
  ['TZ','Tanzânia'],['TL','Timor-Leste'],['TG','Togo'],['TO','Tonga'],['TT','Trinidad e Tobago'],
  ['TN','Tunísia'],['TM','Turcomenistão'],['TR','Turquia'],['TV','Tuvalu'],['UA','Ucrânia'],
  ['UG','Uganda'],['UY','Uruguai'],['UZ','Uzbequistão'],['VU','Vanuatu'],['VA','Vaticano'],
  ['VE','Venezuela'],['VN','Vietnã'],['ZM','Zâmbia'],['ZW','Zimbábue'],
] as const

export type CodigoPaisCatalogo = typeof PAISES_ISO[number][0]
